const KEY='galltracker.entries.v1', SETTINGS='galltracker.settings.v1';
const feelings={0:['😀','Brak objawów'],1:['🙂','Lekki dyskomfort'],2:['😕','Wzdęcia'],3:['😣','Ból brzucha'],4:['🤢','Nudności'],5:['🚨','Silne objawy']};
let entries=load(KEY,[]); let settings=load(SETTINGS,{green:5,yellow:10,lastBackup:null,theme:'light'});
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function load(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
function save(){localStorage.setItem(KEY,JSON.stringify(entries));localStorage.setItem(SETTINGS,JSON.stringify(settings))}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function num(v){return Number(v)||0} function pl(v){return num(v).toLocaleString('pl-PL',{minimumFractionDigits:1,maximumFractionDigits:1})}
function localInputDate(d=new Date()){const z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`}
function risk(v){if(v<=settings.green)return['green','🟢 Niska zawartość'];if(v<=settings.yellow)return['yellow','🟡 Umiarkowana zawartość'];return['red','🔴 Wysoka zawartość']}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2300)}
function go(view){$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${view}`));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'})}
function renderEntry(e,short=false){const [rc,rl]=risk(e.fatPortion);const f=e.feeling===null||e.feeling===undefined?['⏳','Nieocenione']:feelings[e.feeling];return `<article class="entry-card"><div class="entry-top"><div><h3>${esc(e.product)}</h3><div class="entry-meta">${new Date(e.eatenAt).toLocaleString('pl-PL')} · ${pl(e.portion)} g produktu<br>${pl(e.fatPortion)} g tłuszczu w porcji${e.preparation?` · ${esc(e.preparation)}`:''}</div></div><span class="risk-badge ${rc}">${rl}</span></div><p>${f[0]} ${f[1]}${e.delay?` · ${esc(e.delay)}`:''}</p>${e.notes?`<p class="muted">${esc(e.notes)}</p>`:''}${short?'':`<div class="entry-actions"><button class="entry-action" data-edit="${e.id}">Uzupełnij / edytuj</button><button class="entry-action delete" data-delete="${e.id}">Usuń</button></div>`}</article>`}
function todayKey(d){return new Date(d).toLocaleDateString('sv-SE')}
function symptomFreeDays(){const by={};entries.forEach(e=>{if(e.feeling!==null&&e.feeling!==undefined){const k=todayKey(e.eatenAt);by[k]=(by[k]??true)&&e.feeling===0}});const dates=Object.keys(by).sort().reverse();let c=0;for(const d of dates){if(by[d])c++;else break}return c}
function render(){entries.sort((a,b)=>new Date(b.eatenAt)-new Date(a.eatenAt));const tk=todayKey(new Date());const td=entries.filter(e=>todayKey(e.eatenAt)===tk);$('#todayEntries').textContent=td.length;$('#todayFat').textContent=pl(td.reduce((s,e)=>s+num(e.fatPortion),0));$('#symptomFreeDays').textContent=symptomFreeDays();$('#recentEntries').innerHTML=entries.slice(0,3).map(e=>renderEntry(e,true)).join('');renderHistory();renderAnalysis();$('#greenLimit').value=settings.green;$('#yellowLimit').value=settings.yellow;$('#lastBackup').textContent=settings.lastBackup?new Date(settings.lastBackup).toLocaleString('pl-PL'):'brak';save()}
function renderHistory(){const q=$('#historySearch').value.trim().toLowerCase(),filter=$('#historyFilter').value;const list=entries.filter(e=>e.product.toLowerCase().includes(q)).filter(e=>filter==='all'||(filter==='none'&&e.feeling===0)||(filter==='pending'&&(e.feeling===null||e.feeling===undefined))||(filter==='symptoms'&&e.feeling>0));$('#historyList').innerHTML=list.map(e=>renderEntry(e)).join('')}
function renderAnalysis(){const rated=entries.filter(e=>e.feeling!==null&&e.feeling!==undefined);$('#totalEntries').textContent=entries.length;$('#symptomaticEntries').textContent=rated.filter(e=>e.feeling>0).length;$('#averageFat').textContent=pl(entries.length?entries.reduce((s,e)=>s+num(e.fatPortion),0)/entries.length:0);const groups={};rated.forEach(e=>{const k=e.product.trim().toLowerCase();groups[k]??={name:e.product,count:0,bad:0,sum:0};groups[k].count++;groups[k].bad+=e.feeling>0?1:0;groups[k].sum+=e.feeling});const stats=Object.values(groups).sort((a,b)=>(b.bad/b.count)-(a.bad/a.count));$('#productStats').innerHTML=stats.map(x=>{const p=Math.round(x.bad/x.count*100);return `<div class="stat-row"><div class="stat-head"><strong>${esc(x.name)}</strong><span>${x.count} prób · ${p}% z objawami</span></div><div class="progress"><span style="width:${p}%"></span></div></div>`}).join('');const insights=[];if(rated.length>=3){const low=rated.filter(e=>e.fatPortion<=settings.green),high=rated.filter(e=>e.fatPortion>settings.green);const pct=a=>a.length?Math.round(a.filter(e=>e.feeling>0).length/a.length*100):null;if(low.length&&high.length)insights.push(`Objawy wystąpiły w ${pct(low)}% ocenionych porcji do ${pl(settings.green)} g tłuszczu oraz w ${pct(high)}% porcji powyżej tego progu.`);if(stats[0]&&stats[0].count>=2)insights.push(`${stats[0].name}: ${stats[0].bad} z ${stats[0].count} ocenionych wpisów wiązało się z objawami.`)}$('#insightsList').innerHTML=insights.map(x=>`<div class="insight">${esc(x)}</div>`).join('')}
function preview(){const v=num($('#fatPer100').value)*num($('#portion').value)/100;$('#calculatedFat').textContent=pl(v);const b=$('#riskBadge');if(!$('#fatPer100').value||!$('#portion').value){b.className='risk-badge neutral';b.textContent='Uzupełnij dane'}else{const r=risk(v);b.className=`risk-badge ${r[0]}`;b.textContent=r[1]}}
function modalEdit(id){const e=entries.find(x=>x.id===id);if(!e)return;$('#modalContent').innerHTML=`<h2>${esc(e.product)}</h2><p class="muted">Zmień ocenę samopoczucia dla tego wpisu.</p><div class="field"><label for="modalFeeling">Samopoczucie</label><select id="modalFeeling"><option value="">Nieocenione</option>${Object.entries(feelings).map(([k,v])=>`<option value="${k}" ${e.feeling==k?'selected':''}>${v[0]} ${v[1]}</option>`).join('')}</select></div><div class="field"><label for="modalNotes">Notatka</label><textarea id="modalNotes" rows="4">${esc(e.notes||'')}</textarea></div><button id="saveEdit" class="primary-button">Zapisz zmianę</button>`;$('#modal').classList.remove('hidden');$('#saveEdit').onclick=()=>{const v=$('#modalFeeling').value;e.feeling=v===''?null:Number(v);e.notes=$('#modalNotes').value.trim();$('#modal').classList.add('hidden');render();toast('Zmieniono wpis')}}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}
$$('.nav-item').forEach(b=>b.onclick=()=>go(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#fatPer100').oninput=preview;$('#portion').oninput=preview;$('#eatenAt').value=localInputDate();
$('#entryForm').onsubmit=e=>{e.preventDefault();const feeling=document.querySelector('input[name="feeling"]:checked');const fat100=num($('#fatPer100').value),portion=num($('#portion').value);entries.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),product:$('#productName').value.trim(),fat100,portion,fatPortion:fat100*portion/100,eatenAt:$('#eatenAt').value,preparation:document.querySelector('input[name="preparation"]:checked')?.value||'',feeling:feeling?Number(feeling.value):null,delay:$('#symptomDelay').value,notes:$('#notes').value.trim()});e.target.reset();$('#eatenAt').value=localInputDate();preview();render();go('today');toast('Wpis zapisany')};
$('#historySearch').oninput=renderHistory;$('#historyFilter').onchange=renderHistory;$('#historyList').onclick=e=>{const del=e.target.dataset.delete,edit=e.target.dataset.edit;if(del&&confirm('Usunąć ten wpis?')){entries=entries.filter(x=>x.id!==del);render();toast('Wpis usunięty')}if(edit)modalEdit(edit)};
$('#closeModal').onclick=()=>$('#modal').classList.add('hidden');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.add('hidden')};
$('#saveThresholds').onclick=()=>{const g=num($('#greenLimit').value),y=num($('#yellowLimit').value);if(g<0||y<=g)return toast('Żółty próg musi być wyższy');settings.green=g;settings.yellow=y;render();toast('Progi zapisane')};
$('#exportJson').onclick=()=>{settings.lastBackup=new Date().toISOString();save();download(`galltracker-backup-${todayKey(new Date())}.json`,JSON.stringify({app:'GallTracker',version:1,exportedAt:settings.lastBackup,settings,entries},null,2),'application/json');render();toast('Kopia JSON pobrana')};
$('#importJson').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(!Array.isArray(data.entries))throw Error();if(!confirm(`Import zawiera ${data.entries.length} wpisów. Zastąpić obecne dane?`))return;entries=data.entries;settings={...settings,...(data.settings||{})};render();toast('Dane zaimportowane')}catch{alert('Nieprawidłowy plik kopii GallTracker')}finally{e.target.value=''}};
$('#exportCsv').onclick=()=>{const q=v=>`"${String(v??'').replaceAll('"','""')}"`;const rows=[['Data','Produkt','Tłuszcz na 100 g','Porcja g','Tłuszcz w porcji g','Przygotowanie','Samopoczucie','Czas objawów','Notatka'],...entries.map(e=>[e.eatenAt,e.product,e.fat100,e.portion,e.fatPortion,e.preparation,e.feeling==null?'Nieocenione':feelings[e.feeling][1],e.delay,e.notes])];download(`galltracker-${todayKey(new Date())}.csv`,'\ufeff'+rows.map(r=>r.map(q).join(';')).join('\n'),'text/csv;charset=utf-8')};
$('#clearData').onclick=()=>{if(confirm('Usunąć wszystkie wpisy?')){entries=[];render();toast('Dane usunięte')}};
$('#themeToggle').onclick=()=>{settings.theme=settings.theme==='dark'?'light':'dark';document.body.classList.toggle('dark',settings.theme==='dark');save()};document.body.classList.toggle('dark',settings.theme==='dark');render();
